name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      # don't upload the artifacts if it's a pull request
      if: ${{ !github.event.pull_request }}
      with:
      path: 'BWMX/build/outputs/apk/release/*.apk'
      name: 'BWMX-release-${{ github.event.head_commit.id }}
