name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout Android Keystore
        uses: actions/checkout@v3
        with:
        repository: BeiWeiMengXin/keystore #存储android打包用的key的仓库（格式：用户名/仓库名）
        token: ${{ secrets.TOKEN }} # 连接仓库的token,需要单独配置
        path: keystore
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      # don't upload the artifacts if it's a pull request
      if: ${{ !github.event.pull_request }}
      with:
        path: 'app/build/outputs/apk/release/*.apk'
        name: 萌块-release
